# -*- coding: utf-8 -*-
"""train_Test_splitencodingpandasprofilingcrosstab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJdsppdKbOx_eor3hxtwZBwcbo23BxRM
"""

import pandas as pd



df = pd.read_csv('/content/drive/MyDrive/Biology/proj.csv')

from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.30, stratify=df.iloc[:, -1])

train.to_csv('train.csv', index=False)
!cp train.csv /content/drive/MyDrive/Biology/

test.to_csv('test.csv', index=False)
!cp test.csv /content/drive/MyDrive/Biology/